services:
  app:
    build: 
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_INFINISPAN_CLIENT_HOSTS=infinispan:11222
      - QUARKUS_INFINISPAN_CLIENT_USERNAME=admin
      - QUARKUS_INFINISPAN_CLIENT_PASSWORD=password
      - QUARKUS_USERNAME_SQL=root
      - QUARKUS_PASSWORD_SQL=Apigraphql123
      - QUARKUS_URL_SQL=jdbc:mysql://mysql:3306
    depends_on:
      - infinispan
      - mysql
    networks:
      - app-network

  infinispan:
    image: quay.io/infinispan/server:15.0
    environment:
      USER: admin
      PASS: password
    ports:
      - "11222:11222"
    networks:
      - app-network
  
  mysql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Catalog
      MYSQL_ROOT_PASSWORD: Apigraphql123
    ports: 
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: